config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes
  root 'notes#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  # make sure user is signed in
  before_action :authenticate_user!, except:[:index]
  # make middleware to protect the notes from being hacked 
  before_action :correct_user, only: [:edit, :update, :show, :destory]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    # @note = Note.new
    # make the new note belong to a user
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    # @note = Note.new(note_params)
    # make the new note belong to a user
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Auth Middleware
  def correct_user
    @note = current_user.notes.find_by(:id => params[:id])
    redirect_to notes_path, notice:"Not Authorized To edit this note" if @note.nil?
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :body, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'My Notes', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to 'Add Note', new_note_path, class: 'nav-link btn btn-link'%>
                </li>
                <li class="nav-item">
                    <%= button_to 'Sign Out', destroy_user_session_path, :method => :delete, class: 'nav-link btn btn-link'%>
                </li>
                <li class="nav-item">
                    <%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link btn btn-link'%>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link btn btn-link'%>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign In', new_user_session_path, class: 'nav-link btn btn-link'%>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/home/about.html.erb
<h1>About page</h1>

app/views/home/index.html.erb
<h1>Notes</h1>
<p>This is an App where you are able to save your notes and be able to access them later</p>
<h4>Please signin/signup</h4>

app/views/layouts/_alerts.html.erb
<br />
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <%= favicon_link_tag asset_path('charlie-rogersLOGO.svg'), :rel => 'icon', :type =>  'image/svg' %>
    <title>Notes</title>
  </head>
  <body>
    <%= render 'home/header' %>
      <div class="container">
        <% if notice %>
          <%= render 'layouts/alerts'%>
        <% end %>
        <%= yield %>
      </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :title %>
    <%= form.text_field :title, class:'form-control', placeholder:'Title' %>
  </div>

  <div class="field form-group">
    <% form.label :body %>
    <%= form.text_area :body, class:'form-control', placeholder:'This is where you add the note', rows: "10"  %>
  </div>

  <div class="field form-group">
    <% form.label :body %>
    <%= form.hidden_field :user_id, :id => :note_user_id, class:'form-control', value:current_user.id, min:current_user.id, max:current_user.id %>
  </div>
  <br />
  <div class="actions">
    <%= form.submit class:'btn btn-primary'%>
  </div>
<% end %>

app/views/notes/edit.html.erb
<br />
<div class="card">
  <h1 class="card-header" style='text-align:center;'>Editing Note</h1>
  <div class="card-body" style='text-align:center;'>
    <%= render 'form', note: @note %>
    <br/>
    <div style='display:flex;'>
        <%= link_to 'Show', @note, class:'btn btn-success' %>
        <p style='margin:auto 3px;'> </p>
        <%= button_to 'Delete', @note, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
        <p style='margin:auto 3px;'> </p>
        <%= link_to 'Back', notes_path, class:'btn btn-dark' %>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<% if user_signed_in? %>
  <br/>
    <h1 style='text-align:center;'>My Notes</h1>
    <br />
    <div class='container' style='display:flex; flex-wrap: wrap; justify-content:center;'>
      <% @notes.each do |note| %>
        <%# make it where a user can only see their own notes %>
        <% if note.user == current_user %>
            <div class="card" style="width: 18rem; margin: 10px;">
              <div class="card-body">
                <h5 class="card-title" style='text-align:center;'><%= link_to note.title, note %></h5>
                <br/>
                <div style='display:flex; justify-content:space-around;'>
                  <%= button_to 'Edit', edit_note_path(note), class:'btn btn-outline-success btn-sm'  %>
                  <%= button_to 'Delete', note, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-outline-danger btn-sm' %>
                </div>
              </div>
            </div>
          <% else %>
          <%# if the user does not have notes %>
            <div>
              <h3>There does not appear to be saved notes for you</h3>
              <p style='text-align:center;'>Please add a note</p>
            </div>
        <% end %>
      <% end %>
    </div>

    <br>
    <div style='display:flex; justify-content:center;'>
      <%= link_to 'New Note', new_note_path, class:'btn btn-primary' %>
    </div>
  <% else %>
  <br/>
  <div class="card">
  <h2 class="card-header" style='text-align:center;'>My Notes</h2>
  <div class="card-body">
    <p class="card-text" style='text-align:center;'>This is an App where you are able to save your notes and be able to access them later</p>
    <p class="card-text" style='text-align:center;'>Please signin/signup</p>
    <div style='display:flex; justify-content:space-around;'>
      <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-success'%>
      <%= button_to 'Sign In', new_user_session_path, class: 'btn btn-primary'%>
    </div>
  </div>
</div>
<% end %>

app/views/notes/new.html.erb
<br />
<h1>Create A Note</h1>
<br />
<%= render 'form', note: @note %>
<br />
<%= link_to 'Back', notes_path, class:'btn btn-dark' %>

app/views/notes/show.html.erb
<br/>
<div class="jumbotron">
  <h1 class="display-4 mx-auto" style = 'width:25%; text-transform: capitalize;'><%= @note.title %></h1>
  <hr class="my-4">
  <p>
    <%= @note.body %> 
  </p>

  <br />
  <br />

  <%= link_to 'Edit', edit_note_path(@note), class:'btn btn-success' %>
  <%= link_to 'Back', notes_path, class:'btn btn-secondary' %>
</div>